# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

dorsal:
    support:
        mail: support@godorsal.com

    application:
        url: app.godorsal.com
        protocol: https

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        url: jdbc:postgresql://dorsal-db-prod-1.cjigsiwzvxbf.us-west-1.rds.amazonaws.com:5432/dorsalprod
        name:
        username: dorsal
        password: dorsal
    jpa:
        database-platform: com.dorsal.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show_sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: smtp.gmail.com
        port: 587
        username: support@godorsal.com
        password: $MacLarenP1$1
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
    tomcat:
            remote_ip_header: x-forwarded-for
            protocol_header: x-forwarded-proto


# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 256M
    security:
        authentication:
            jwt:
                secret: 332fb047a4208836503fe6f789b16513927de45f
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: dorsal@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: dorsal
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    swagger: # swagger is disabled. It can be disabled by pasing 'no-swagger' profile at run time as well
        enabled: false
