version: '2'
services:
    dorsal-app:
        image: dorsal
        external_links:
            - dorsal-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/dorsal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dorsal-postgresql:
        extends:
            file: postgresql.yml
            service: dorsal-postgresql
